import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable}  `}>
        <div className="bg-gradient-to-bl from-[#00224D] to-[#5D0E41] px-2">
          <div className="max-w-7xl mx-auto text-white">
            <Navbar />
            <div
              className=" h-[calc(100vh-90px)]
            flex justify-center items-center
          "
            >
              {children}
            </div>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
